apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
  namespace: app-test
  labels:
    app: welcome
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
        - name: welcome
          image: dddatago/welcome:smallest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              name: welcome-port
          args: ["run"]
          livenessProbe:
            exec:
              command:
                - ./welcome
                - live
          readinessProbe:
            httpGet:
              path: /ready
              port: 8888
          env:
            - name: qihoo_logs_go-quc
              value: "stdout"
            - name: qihoo_logs_go-quc_tags
              value: "app=go-quc,service=gate"
            - name: qihoo_logs_go-quc_target
              value: logtest
---
apiVersion: v1
kind: Service
metadata:
  name: welcome
  namespace: app-test
spec:
  type: NodePort
  ports:
    - name: welcome-port
      port: 80
      protocol: TCP
      targetPort: 8888
      nodePort: 30003
  selector:
    app: welcome
