FROM golang:alpine as builder
RUN apk update && apk add --no-cache git
# Create appuser.
RUN adduser --disabled-passwor --gecos '' appuser
WORKDIR /welcome
COPY . .
RUN GOOS=linux GOARCH=amd64 go build -mod=vendor -ldflags="-w -s" -o app
#RUN go build -mod=vendor --o app
FROM alpine
RUN echo 'Asia/Shanghai' >/etc/timezone
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /welcome/app /home/welcome
USER appuser
ENTRYPOINT ["/home/welcome"]