FROM golang:1.12-stretch as builder
RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates &&  apt-get clean
RUN adduser -D -g '' appuser

WORKDIR /welcome
COPY / .
RUN GOOS=linux GOARCH=amd64 go build -mod=vendor -ldflags="-w -s" -o welcome
FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /welcome/welcome /
CMD ["./welcome"]